### ISSUE TITLE
Unable to add Provider Names 

### ISSUE THREAD

**Issue by ProgramPractice** [brianstringfellow/EtwViewer#1]
Thanks for the tool!, this is very helpful. Here is my first issue : )
Repro Steps:
1.	Clone repository from GitHub
2.	Open solution in Visual Studio.
3.	Set platform to ‘x64’.
4.	Build and run.
5.	Enter the provider names you want to listen for.

Actual Result:
Unable to add Provider Names hence unable to see the traces in the ETWViewer tool

Expected Result
Able to add Provider Names in the UI and should be able to see the traces in ETWViewer tool

**Comment by brianstringfellow** [comment]
On problem I found is that when adding a row and editing the cell value, if the 'Update' button is clicked without the cell losing focus, then the change is not persisted. [https://github.com/brianstringfellow/EtwViewer/commit/23d39afe84fced7b3140d65fdcd5a541be2dd965](url)
Let me know if the problem continues.

**Comment by brianstringfellow** [comment]
Reopening after closing by accident.

**Comment by brianstringfellow** [comment]
Problem fixed.

**Comment by ProgramPractice** [comment]
Thank you, this works!
